name: Build AIducation App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build DMG
        run: cd aiducation && ./gradlew packageDmg --stacktrace

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AIducation-macos
          path: aiducation/composeApp/build/compose/binaries/main/dmg/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build EXE
        run: cd aiducation && ./gradlew packageMsi --stacktrace

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AIducation-windows
          path: aiducation/composeApp/build/compose/binaries/main/msi/*.msi
